[2024-03-01T16:27:51.798+0530] {processor.py:161} INFO - Started process (PID=7836) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:27:51.799+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:27:51.799+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:27:51.799+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:27:51.803+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:27:51.802+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 3, in <module>
    from datatime import datetime
ModuleNotFoundError: No module named 'datatime'
[2024-03-01T16:27:51.803+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:27:51.896+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.100 seconds
[2024-03-01T16:28:47.182+0530] {processor.py:161} INFO - Started process (PID=7897) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:28:47.262+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:28:47.263+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:28:47.263+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:28:47.266+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:28:47.265+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 3, in <module>
    from datatime import datetime
ModuleNotFoundError: No module named 'datatime'
[2024-03-01T16:28:47.266+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:28:47.360+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.180 seconds
[2024-03-01T16:29:25.977+0530] {processor.py:161} INFO - Started process (PID=7942) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:29:26.051+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:29:26.053+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:29:26.052+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:29:26.061+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:29:26.058+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 3, in <module>
    from datatime import datetime
ModuleNotFoundError: No module named 'datatime'
[2024-03-01T16:29:26.062+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:29:26.182+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.208 seconds
[2024-03-01T16:30:08.018+0530] {processor.py:161} INFO - Started process (PID=7991) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:30:08.109+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:30:08.111+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:30:08.110+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:30:08.120+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:30:08.117+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 8, in <module>
    with DAG(gag_id="hello_world",
         ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'gag_id'
[2024-03-01T16:30:08.121+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:30:08.231+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.220 seconds
[2024-03-01T16:30:53.084+0530] {processor.py:161} INFO - Started process (PID=8262) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:30:53.110+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:30:53.112+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:30:53.111+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:30:53.120+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:30:53.118+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 8, in <module>
    with DAG(gag_id="hello_world",
         ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'gag_id'
[2024-03-01T16:30:53.121+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:30:53.270+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.192 seconds
[2024-03-01T16:31:28.796+0530] {processor.py:161} INFO - Started process (PID=8587) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:31:28.817+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:31:28.819+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:31:28.818+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:31:28.823+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:31:28.822+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 8, in <module>
    with DAG(gag_id="hello_world",
         ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'gag_id'
[2024-03-01T16:31:28.823+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:31:28.925+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.131 seconds
[2024-03-01T16:32:25.271+0530] {processor.py:161} INFO - Started process (PID=9253) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:32:25.291+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:32:25.291+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:32:25.291+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:32:25.322+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:32:25.307+0530] {dagbag.py:350} ERROR - Failed to import: /home/akranth/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/akranth/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/akranth/airflow/dags/hello_world.py", line 8, in <module>
    with DAG(dag_id="hello_world",
         ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'start_data'
[2024-03-01T16:32:25.324+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:32:25.435+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.166 seconds
[2024-03-01T16:33:12.325+0530] {processor.py:161} INFO - Started process (PID=9339) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:33:12.327+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:33:12.329+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.328+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:33:12.346+0530] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:33:12.697+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.696+0530] {override.py:1769} INFO - Created Permission View: can read on DAG:hello_world
[2024-03-01T16:33:12.796+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.796+0530] {override.py:1769} INFO - Created Permission View: can edit on DAG:hello_world
[2024-03-01T16:33:12.889+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.888+0530] {override.py:1769} INFO - Created Permission View: can delete on DAG:hello_world
[2024-03-01T16:33:12.891+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.890+0530] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-01T16:33:12.910+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.910+0530] {dag.py:3069} INFO - Creating ORM DAG for hello_world
[2024-03-01T16:33:12.924+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:12.924+0530] {dag.py:3834} INFO - Setting next_dagrun for hello_world to 2024-03-03 00:00:00+00:00, run_after=2024-03-03 01:00:00+00:00
[2024-03-01T16:33:13.115+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.795 seconds
[2024-03-01T16:33:54.929+0530] {processor.py:161} INFO - Started process (PID=9407) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:33:54.942+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:33:54.943+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:54.943+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:33:54.950+0530] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:33:54.966+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:54.966+0530] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-01T16:33:54.988+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:33:54.988+0530] {dag.py:3834} INFO - Setting next_dagrun for hello_world to 2024-03-03 00:00:00+00:00, run_after=2024-03-03 01:00:00+00:00
[2024-03-01T16:33:55.106+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.180 seconds
[2024-03-01T16:34:37.452+0530] {processor.py:161} INFO - Started process (PID=9538) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:34:37.480+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:34:37.482+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:34:37.481+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:34:37.498+0530] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:34:37.515+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:34:37.515+0530] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-01T16:34:37.618+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:34:37.617+0530] {dag.py:3834} INFO - Setting next_dagrun for hello_world to 2024-03-03 00:00:00+00:00, run_after=2024-03-03 01:00:00+00:00
[2024-03-01T16:34:37.782+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.335 seconds
[2024-03-01T16:35:11.065+0530] {processor.py:161} INFO - Started process (PID=9606) to work on /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:35:11.081+0530] {processor.py:830} INFO - Processing file /home/akranth/airflow/dags/hello_world.py for tasks to queue
[2024-03-01T16:35:11.084+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:35:11.083+0530] {dagbag.py:540} INFO - Filling up the DagBag from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:35:11.103+0530] {processor.py:840} INFO - DAG(s) 'hello_world' retrieved from /home/akranth/airflow/dags/hello_world.py
[2024-03-01T16:35:11.120+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:35:11.119+0530] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-01T16:35:11.140+0530] {logging_mixin.py:188} INFO - [2024-03-01T16:35:11.140+0530] {dag.py:3834} INFO - Setting next_dagrun for hello_world to 2024-03-03 00:00:00+00:00, run_after=2024-03-03 01:00:00+00:00
[2024-03-01T16:35:11.259+0530] {processor.py:183} INFO - Processing /home/akranth/airflow/dags/hello_world.py took 0.198 seconds
